### ISSUE TITLE
feature request: Add live-server UI element in Lualine

### ISSUE THREAD

**Issue by tiendat306** [d-vegapunk/live-server.nvim#1]
**Summary**
Add an icon in lualine to display the live-server connection status. The icon should indicate the server status with colors and provide information about the port of connection. Additionally, the icon should be clickable to toggle the live-server start or stop.

**Proposed Implementation**

- Icon Design:
    - A simple icon (e.g., a computer monitor or server icon) can be used.
    - The icon color changes based on the connection status
    - When connected, the port number should be displayed next to the icon.
- Click Functionality:
    - Add a click event to the icon that toggles the live-server status (start/stop).
    - Ensure that the status change is reflected in real-time in lualine.

_Please let me know if any further information is needed or if there are any questions regarding this feature request. Thank you for considering this enhancement !_

**Comment by d-vegapunk** [comment]
Thank you for the excellent suggestion. I will keep this issue updated with my progress.
